services:
  db:
    image: postgres
    container_name: db_imprimirme
    ports:
      - "5434:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=imprimirme"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres", "-d", "imprimirme"]
      interval: 3s
      timeout: 30s
      retries: 10
    volumes:
      - "./data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"

  app:
    build: .
    container_name: back_imprimirme
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: "service_healthy"
