version: "2.1"
services:
  app:
    build: .
    container_name: back_imprimirme
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: "service_healthy"

  db:
    image: postgres:14
    restart: always
    container_name: db_imprimirme
    ports:
      - "5434:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=imprimirme"
    # Como no database.py já está sendo feito Base.metadata.create_all(engine), as tabelas já são criadas
    # automaticamente pelo SQLAlchemy, não precisa rodar SQL pra criar elas junto com a inicialização do DB.
    #volumes:
    # - "./data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres", "-d", "imprimirme"]
      interval: 3s
      timeout: 30s
      retries: 10

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
